### ISSUE TITLE
Secrets in `imagePullSecrets`  are not detected as in use.

### ISSUE THREAD

**Issue by elonzh** [micnncim/kubectl-reap#120]
```yaml
    spec:
      imagePullSecrets:
        - name: coding-devos-regcred
```

```
secret/coding-devos-regcred deleted (dry run)
```
